title: "General Discussion"
labels: ["discussion"]
body: |
  ## Guidelines

  Please familiarize yourself with our [Code of Conduct](https://whatwg.org/code-of-conduct) before participating.

  ## Topic

  Use this space to discuss anything related to the HTML Standard that doesn't fit into other categories.

  **What would you like to discuss?**